package com.toss.tosspaybackend.domain.member.enums;

public enum Nationality {
    AFGHANISTAN, ALBANIA, ALGERIA, ARGENTINA, AUSTRALIA, AUSTRIA,
    BANGLADESH, BELGIUM, BRAZIL,
    CANADA, CHINA, COLOMBIA,
    DENMARK,
    EGYPT,
    FINLAND, FRANCE,
    GERMANY, GREECE,
    HUNGARY,
    INDIA, INDONESIA, IRAN, IRELAND, ITALY,
    JAPAN,
    KENYA, KOREA,
    MALAYSIA, MEXICO,
    NETHERLANDS, NEW_ZEALAND, NIGERIA, NORWAY,
    PAKISTAN, PERU, PHILIPPINES, POLAND, PORTUGAL,
    RUSSIA,
    SAUDI_ARABIA, SINGAPORE, SOUTH_AFRICA, SPAIN, SWEDEN, SWITZERLAND,
    TAIWAN, THAILAND, TURKEY,
    UNITED_KINGDOM, UNITED_STATES,
    VIETNAM
}